// Native Rust plugin host for PhazeAI IDE.
//
// Plugins are compiled as cdylib crates that depend on `phazeai-plugin-api`.
// Each plugin directory must contain:
//   - `plugin.toml`       – plugin manifest (parsed as `PluginManifest`)
//   - `lib<name>.so`      – shared library (Linux)
//   - `lib<name>.dylib`   – shared library (macOS)
//   - `<name>.dll`        – shared library (Windows)
//
// The loader calls three `extern "C"` symbols exported from the library
// (generated by the `declare_plugin!` macro in phazeai-plugin-api):
//   - `_phazeai_plugin_api_version() -> u32`
//   - `_phazeai_plugin_create()      -> *mut dyn PhazePlugin`
//   - `_phazeai_plugin_destroy(ptr: *mut dyn PhazePlugin)`

// Keep empty stub modules so existing `pub mod` declarations do not break.
pub mod js;
pub mod vsix;
pub mod wasm;

// VSCode extension asset loading (themes, grammars, snippets, language configs)
pub mod asset_loader;
pub mod registry;
pub mod theme_convert;
pub mod vscode_assets;

pub use phazeai_plugin_api::{
    PhazePlugin, PluginCommand, PluginEvent, PluginHost, PluginManifest, API_VERSION,
};

use libloading::{Library, Symbol};
use serde::Serialize;
use std::path::{Path, PathBuf};
use tracing::{error, info, warn};

// ---------------------------------------------------------------------------
// IdeDelegate – backward-compat trait used by the UI layer
// ---------------------------------------------------------------------------

/// A trait that the UI layer implements to provide IDE functionality to the
/// extension host. It mirrors `PluginHost` but is object-safe with `Arc`.
pub trait IdeDelegate: Send + Sync {
    fn log(&self, msg: &str);
    fn show_message(&self, msg: &str);
    fn get_active_text(&self) -> String;
}

/// A default no-op implementation used when no real delegate is provided.
pub struct DummyDelegate;

impl IdeDelegate for DummyDelegate {
    fn log(&self, msg: &str) {
        info!("[IDE] {}", msg);
    }
    fn show_message(&self, msg: &str) {
        info!("[IDE Message] {}", msg);
    }
    fn get_active_text(&self) -> String {
        String::new()
    }
}

// ---------------------------------------------------------------------------
// IdeDelegateHost – bridges IdeDelegate into the PluginHost trait
// ---------------------------------------------------------------------------

/// Wraps an `Arc<dyn IdeDelegate>` and implements `PluginHost` so that the
/// plugin manager can pass it to plugin `on_activate` / `on_deactivate`.
pub struct IdeDelegateHost {
    delegate: std::sync::Arc<dyn IdeDelegate>,
}

impl IdeDelegateHost {
    pub fn new(delegate: std::sync::Arc<dyn IdeDelegate>) -> Self {
        Self { delegate }
    }
}

impl PluginHost for IdeDelegateHost {
    fn log(&self, _level: u8, msg: &str) {
        self.delegate.log(msg);
    }

    fn show_message(&self, msg: &str) {
        self.delegate.show_message(msg);
    }

    fn get_active_text(&self) -> String {
        self.delegate.get_active_text()
    }

    fn get_active_file_path(&self) -> String {
        String::new()
    }

    fn insert_text(&self, _text: &str) {}

    fn execute_command(&self, _cmd: &str, _args: &str) -> Result<String, String> {
        Err("Not implemented in DummyDelegate bridge".to_string())
    }
}

// ---------------------------------------------------------------------------
// NativePlugin – owns the loaded library and the plugin trait object
// ---------------------------------------------------------------------------

/// A successfully loaded native plugin. Dropping this value calls
/// `on_deactivate` on the plugin and then `_phazeai_plugin_destroy` before
/// the shared library is unloaded.
pub struct NativePlugin {
    pub manifest: PluginManifest,
    /// The raw plugin object. Valid while `library` is loaded.
    ///
    /// # Safety
    ///
    /// This pointer is obtained from `_phazeai_plugin_create` and must be
    /// freed via `_phazeai_plugin_destroy` from the same library before
    /// `library` is dropped.  We never let this pointer escape the struct.
    plugin: *mut dyn PhazePlugin,
    /// Must be dropped *after* `plugin` has been destroyed.
    library: Library,
    pub active: bool,
}

// SAFETY: The plugin pointer is fully owned by this struct and never
// accessed concurrently. We synchronize all access through &mut self.
unsafe impl Send for NativePlugin {}
unsafe impl Sync for NativePlugin {}

impl NativePlugin {
    /// Call `on_deactivate` and flag the plugin as inactive.
    pub fn deactivate(&mut self) {
        if self.active {
            // SAFETY: `plugin` is a valid, non-null pointer for the
            // lifetime of `library`, which is still loaded here.
            unsafe { (*self.plugin).on_deactivate() };
            self.active = false;
        }
    }

    /// Return the commands this plugin contributes, or an empty vec if the
    /// plugin has already been deactivated.
    pub fn commands(&self) -> Vec<PluginCommand> {
        if self.active {
            // SAFETY: pointer is valid while active.
            unsafe { (*self.plugin).commands() }
        } else {
            Vec::new()
        }
    }

    /// Forward a command execution to the plugin.
    pub fn execute_command(&mut self, cmd: &str, args: &str) -> Result<String, String> {
        if !self.active {
            return Err(format!("Plugin '{}' is not active", self.manifest.name));
        }
        // SAFETY: pointer is valid while active.
        unsafe { (*self.plugin).execute_command(cmd, args) }
    }

    /// Deliver an IDE event to the plugin.
    pub fn on_event(&mut self, event: &PluginEvent) {
        if self.active {
            // SAFETY: pointer is valid while active.
            unsafe { (*self.plugin).on_event(event) };
        }
    }
}

impl Drop for NativePlugin {
    fn drop(&mut self) {
        // Deactivate before destroying the object.
        self.deactivate();

        // Resolve and call the destroy function from the library while the
        // library is still open.
        //
        // SAFETY: We are inside `drop`, so no other code can be using the
        // pointer. `library` is still valid at this point because it is a
        // field of the same struct and Rust drops fields in declaration order.
        unsafe {
            let destroy_result: Result<Symbol<unsafe extern "C" fn(*mut dyn PhazePlugin)>, _> =
                self.library.get(b"_phazeai_plugin_destroy");

            match destroy_result {
                Ok(destroy) => destroy(self.plugin),
                Err(e) => error!(
                    "Failed to resolve _phazeai_plugin_destroy for '{}': {}",
                    self.manifest.name, e
                ),
            }
        }
        // `library` is dropped here, unloading the shared object.
    }
}

// ---------------------------------------------------------------------------
// PluginInfo – serialisable summary for the UI plugin manager
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, Serialize)]
pub struct PluginInfo {
    pub name: String,
    pub version: String,
    pub description: String,
    pub author: String,
    pub active: bool,
    pub commands: Vec<PluginCommand>,
}

// ---------------------------------------------------------------------------
// ExtensionManager
// ---------------------------------------------------------------------------

/// Manages all loaded native plugins.
pub struct ExtensionManager {
    plugins: Vec<NativePlugin>,
    /// Root directory scanned for plugin subdirectories.
    pub plugin_dir: PathBuf,
}

impl ExtensionManager {
    /// Create a new manager with the default plugin directory
    /// (`~/.phazeai/plugins/`).
    pub fn new() -> Self {
        let plugin_dir = dirs::home_dir()
            .unwrap_or_else(|| PathBuf::from("."))
            .join(".phazeai")
            .join("plugins");

        Self {
            plugins: Vec::new(),
            plugin_dir,
        }
    }

    /// Create a manager that scans a custom directory.
    pub fn with_plugin_dir(plugin_dir: impl Into<PathBuf>) -> Self {
        Self {
            plugins: Vec::new(),
            plugin_dir: plugin_dir.into(),
        }
    }

    // -----------------------------------------------------------------------
    // Plugin loading
    // -----------------------------------------------------------------------

    /// Load a single plugin from `dir`.
    ///
    /// The directory must contain a `plugin.toml` manifest and the
    /// platform-appropriate shared library file.
    pub fn load_plugin(&mut self, dir: &Path, host: &dyn PluginHost) -> Result<(), String> {
        // 1. Read and parse the manifest.
        let manifest_path = dir.join("plugin.toml");
        if !manifest_path.exists() {
            return Err(format!("No plugin.toml found in {}", dir.display()));
        }

        let manifest_str = std::fs::read_to_string(&manifest_path)
            .map_err(|e| format!("Failed to read plugin.toml: {}", e))?;

        let manifest: PluginManifest =
            toml::from_str(&manifest_str).map_err(|e| format!("Invalid plugin.toml: {}", e))?;

        // 2. Resolve the library path.
        let lib_path = match &manifest.library {
            Some(explicit) => dir.join(explicit),
            None => dir.join(platform_lib_name(&manifest.name)),
        };

        if !lib_path.exists() {
            return Err(format!("Plugin library not found: {}", lib_path.display()));
        }

        // SAFETY: We are loading an untrusted shared library.  The caller is
        // responsible for ensuring the library is from a trustworthy source.
        // Once loaded we immediately check the API version before doing
        // anything else so that mismatched plugins fail fast.
        let library = unsafe {
            Library::new(&lib_path)
                .map_err(|e| format!("Failed to load library {}: {}", lib_path.display(), e))?
        };

        // 3. Check API version.
        let reported_version: u32 = unsafe {
            let api_version_fn: Symbol<unsafe extern "C" fn() -> u32> = library
                .get(b"_phazeai_plugin_api_version")
                .map_err(|e| format!("Missing _phazeai_plugin_api_version: {}", e))?;
            api_version_fn()
        };

        if reported_version < manifest.min_api_version {
            return Err(format!(
                "Plugin '{}' requires API version >= {} but reported {}",
                manifest.name, manifest.min_api_version, reported_version
            ));
        }

        if reported_version != API_VERSION {
            return Err(format!(
                "Plugin '{}' was compiled against API version {} but host is version {}",
                manifest.name, reported_version, API_VERSION
            ));
        }

        // 4. Create the plugin object.
        let plugin_ptr: *mut dyn PhazePlugin = unsafe {
            let create_fn: Symbol<unsafe extern "C" fn() -> *mut dyn PhazePlugin> = library
                .get(b"_phazeai_plugin_create")
                .map_err(|e| format!("Missing _phazeai_plugin_create: {}", e))?;
            let ptr = create_fn();
            if ptr.is_null() {
                return Err(format!(
                    "_phazeai_plugin_create returned null for '{}'",
                    manifest.name
                ));
            }
            ptr
        };

        // 5. Activate.
        // SAFETY: `plugin_ptr` is a fresh, valid pointer returned one line ago.
        unsafe { (*plugin_ptr).on_activate(host) };

        let name = manifest.name.clone();
        self.plugins.push(NativePlugin {
            manifest,
            plugin: plugin_ptr,
            library,
            active: true,
        });

        info!("Loaded plugin '{}'", name);
        Ok(())
    }

    /// Deactivate and unload the plugin with the given name.
    pub fn unload_plugin(&mut self, name: &str) {
        if let Some(pos) = self.plugins.iter().position(|p| p.manifest.name == name) {
            let mut plugin = self.plugins.remove(pos);
            plugin.deactivate();
            // `NativePlugin::drop` calls destroy + unloads the library.
            drop(plugin);
            info!("Unloaded plugin '{}'", name);
        } else {
            warn!("unload_plugin: no plugin named '{}'", name);
        }
    }

    /// Scan `plugin_dir` for sub-directories that contain a `plugin.toml`
    /// and load each one.  Directories that fail to load are skipped with a
    /// warning rather than aborting the whole scan.
    pub fn scan_plugins(&mut self, host: &dyn PluginHost) {
        let dir = self.plugin_dir.clone();
        if !dir.exists() {
            info!(
                "Plugin directory does not exist, skipping scan: {}",
                dir.display()
            );
            return;
        }

        let entries = match std::fs::read_dir(&dir) {
            Ok(e) => e,
            Err(e) => {
                error!("Failed to read plugin directory {}: {}", dir.display(), e);
                return;
            }
        };

        for entry in entries.flatten() {
            let path = entry.path();
            if !path.is_dir() {
                continue;
            }
            if !path.join("plugin.toml").exists() {
                continue;
            }
            // Skip already-loaded plugins (by matching directory name / plugin name).
            let dir_name = path
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("")
                .to_string();
            if self
                .plugins
                .iter()
                .any(|p| p.manifest.name == dir_name || p.manifest.name == path.to_string_lossy())
            {
                continue;
            }

            if let Err(e) = self.load_plugin(&path, host) {
                warn!("Failed to load plugin from {}: {}", path.display(), e);
            }
        }
    }

    // -----------------------------------------------------------------------
    // Queries
    // -----------------------------------------------------------------------

    /// Return a summary of all currently loaded plugins.
    pub fn get_plugins(&self) -> Vec<PluginInfo> {
        self.plugins
            .iter()
            .map(|p| PluginInfo {
                name: p.manifest.name.clone(),
                version: p.manifest.version.clone(),
                description: p.manifest.description.clone(),
                author: p.manifest.author.clone(),
                active: p.active,
                commands: p.commands(),
            })
            .collect()
    }

    // -----------------------------------------------------------------------
    // Command dispatch
    // -----------------------------------------------------------------------

    /// Route a command to the plugin that registered it.
    ///
    /// `args` should be a JSON string, e.g. `"{}"` for no arguments.
    pub fn execute_command(&mut self, cmd: &str, args: &str) -> Result<String, String> {
        for plugin in &mut self.plugins {
            if !plugin.active {
                continue;
            }
            let has_cmd = plugin.commands().iter().any(|c| c.id == cmd);
            if has_cmd {
                return plugin.execute_command(cmd, args);
            }
        }
        Err(format!("No plugin handles command '{}'", cmd))
    }

    // -----------------------------------------------------------------------
    // Event broadcasting
    // -----------------------------------------------------------------------

    /// Deliver an IDE event to every active plugin.
    pub fn broadcast_event(&mut self, event: &PluginEvent) {
        for plugin in &mut self.plugins {
            plugin.on_event(event);
        }
    }

    // -----------------------------------------------------------------------
    // Hot reload
    // -----------------------------------------------------------------------

    /// Unload then reload the named plugin.
    pub fn reload_plugin(&mut self, name: &str, host: &dyn PluginHost) -> Result<(), String> {
        // Find the directory the plugin was loaded from so we can reload it.
        let dir = self
            .plugins
            .iter()
            .find(|p| p.manifest.name == name)
            .ok_or_else(|| format!("No plugin named '{}' to reload", name))
            .map(|_| self.plugin_dir.join(name))?;

        self.unload_plugin(name);
        self.load_plugin(&dir, host)
    }
}

impl Default for ExtensionManager {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Platform helpers
// ---------------------------------------------------------------------------

/// Return the conventional shared library file name for `plugin_name` on the
/// current target platform.
fn platform_lib_name(plugin_name: &str) -> String {
    #[cfg(target_os = "linux")]
    {
        format!("lib{}.so", plugin_name)
    }
    #[cfg(target_os = "macos")]
    {
        format!("lib{}.dylib", plugin_name)
    }
    #[cfg(target_os = "windows")]
    {
        format!("{}.dll", plugin_name)
    }
    #[cfg(not(any(target_os = "linux", target_os = "macos", target_os = "windows")))]
    {
        // Fallback for other Unix-like systems.
        format!("lib{}.so", plugin_name)
    }
}
