use crate::app::VimMotion;
use crate::lsp_bridge::{
    CodeAction, CodeLensEntry, CompletionEntry, DefinitionResult, DiagEntry, InlayHintEntry,
    ReferenceEntry, SymbolEntry,
};
use floem::reactive::RwSignal;
use std::path::PathBuf;

#[derive(Clone)]
pub struct EditorState {
    pub open_file: RwSignal<Option<PathBuf>>,
    pub open_tabs: RwSignal<Vec<PathBuf>>,
    pub active_cursor: RwSignal<Option<(PathBuf, u32, u32)>>,
    pub vim_mode: RwSignal<bool>,
    pub vim_normal_mode: RwSignal<bool>,
    pub vim_pending_key: RwSignal<Option<char>>,
    pub vim_motion: RwSignal<Option<VimMotion>>,
    pub vim_visual_mode: RwSignal<bool>,
    pub vim_visual_line: RwSignal<bool>,
    pub vim_marks: RwSignal<std::collections::HashMap<char, (PathBuf, usize)>>,
    pub vim_last_motion: RwSignal<Option<VimMotion>>,
    pub vim_ex_open: RwSignal<bool>,
    pub vim_ex_input: RwSignal<String>,
    pub font_size: RwSignal<u32>,
    pub tab_size: RwSignal<u32>,
    pub auto_save: RwSignal<bool>,
    pub word_wrap: RwSignal<bool>,
    pub relative_line_numbers: RwSignal<bool>,
    pub line_ending: RwSignal<&'static str>,
    pub active_readonly: RwSignal<bool>,

    // LSP & Intelligence
    pub diagnostics: RwSignal<Vec<DiagEntry>>,
    pub completions: RwSignal<Vec<CompletionEntry>>,
    pub completion_open: RwSignal<bool>,
    pub completion_selected: RwSignal<usize>,
    pub completion_filter_text: RwSignal<String>,
    pub hover_text: RwSignal<Option<String>>,
    pub goto_line: RwSignal<u32>,
    pub goto_definition: RwSignal<Option<DefinitionResult>>,
    pub references: RwSignal<Vec<ReferenceEntry>>,
    pub references_visible: RwSignal<bool>,
    pub code_actions: RwSignal<Vec<CodeAction>>,
    pub code_actions_open: RwSignal<bool>,
    pub doc_symbols: RwSignal<Vec<SymbolEntry>>,
    pub inlay_hints: RwSignal<Vec<InlayHintEntry>>,
    pub code_lens: RwSignal<Vec<CodeLensEntry>>,
    pub folding_ranges: RwSignal<Vec<(u32, u32)>>,

    // Nonces & Actions
    pub comment_toggle_nonce: RwSignal<u64>,
    pub ctrl_d_nonce: RwSignal<u64>,
    pub fold_nonce: RwSignal<u64>,
    pub unfold_nonce: RwSignal<u64>,
    pub fold_all_nonce: RwSignal<u64>,
    pub unfold_all_nonce: RwSignal<u64>,
    pub move_line_up_nonce: RwSignal<u64>,
    pub move_line_down_nonce: RwSignal<u64>,
    pub duplicate_line_nonce: RwSignal<u64>,
    pub delete_line_nonce: RwSignal<u64>,
    pub transform_upper_nonce: RwSignal<u64>,
    pub transform_lower_nonce: RwSignal<u64>,
    pub transform_title_nonce: RwSignal<u64>,
    pub join_line_nonce: RwSignal<u64>,
    pub sort_lines_nonce: RwSignal<u64>,
    pub format_selection_nonce: RwSignal<u64>,
    pub split_editor: RwSignal<bool>,
    pub active_blame: RwSignal<String>,
    pub pending_completion: RwSignal<Option<(String, usize)>>,
    pub yank_ring: RwSignal<Vec<String>>,
    pub yank_ring_idx: RwSignal<usize>,
    pub split_editor_down: RwSignal<bool>,

    // LSP & Overlays
    pub rename_open: RwSignal<bool>,
    pub rename_query: RwSignal<String>,
    pub rename_target: RwSignal<String>,
    pub sig_help: RwSignal<Option<crate::lsp_bridge::SignatureHelpResult>>,
    pub ws_syms_open: RwSignal<bool>,
    pub ws_syms_query: RwSignal<String>,
    pub workspace_symbols: RwSignal<Vec<crate::lsp_bridge::SymbolEntry>>,
    pub goto_overlay_open: RwSignal<bool>,
    pub goto_overlay_input: RwSignal<String>,
    pub peek_def_open: RwSignal<bool>,
    pub peek_def_lines: RwSignal<Vec<String>>,

    // Nonces & Toggles
    pub col_cursor_up_nonce: RwSignal<u64>,
    pub col_cursor_down_nonce: RwSignal<u64>,
    pub sticky_lines: RwSignal<Vec<String>>,
    pub expand_selection_nonce: RwSignal<u64>,
    pub shrink_selection_nonce: RwSignal<u64>,
    pub save_no_format_nonce: RwSignal<u64>,
    pub code_lens_visible: RwSignal<bool>,
    pub organize_imports_on_save: RwSignal<bool>,
    pub inlay_hints_sig: RwSignal<Vec<crate::lsp_bridge::InlayHintEntry>>,
    pub inlay_hints_toggle: RwSignal<bool>,
    pub minimap_visible: RwSignal<bool>,

    // Split View State
    pub split_open_file: RwSignal<Option<PathBuf>>,
    pub split_active_cursor: RwSignal<Option<(PathBuf, u32, u32)>>,
    pub split_open_tabs: RwSignal<Vec<PathBuf>>,
    pub split_down_file: RwSignal<Option<PathBuf>>,
    pub split_down_cursor: RwSignal<Option<(PathBuf, u32, u32)>>,
    pub split_down_tabs: RwSignal<Vec<PathBuf>>,
}
