use serde::{Deserialize, Serialize};

/// Current plugin API version. Plugins must match this to be loaded.
pub const API_VERSION: u32 = 1;

/// What the host exposes to plugins. Plugins receive a reference to this
/// during activation and may call into it at any time while active.
pub trait PluginHost {
    /// Emit a log message. `level` follows the conventional log levels:
    /// 0 = error, 1 = warn, 2 = info, 3 = debug, 4 = trace.
    fn log(&self, level: u8, msg: &str);

    /// Display a brief informational message to the user (e.g. status bar
    /// toast or notification).
    fn show_message(&self, msg: &str);

    /// Return the text currently selected in the active editor, or an empty
    /// string if nothing is selected.
    fn get_active_text(&self) -> String;

    /// Return the absolute file-system path of the file open in the active
    /// editor tab, or an empty string if no file is open.
    fn get_active_file_path(&self) -> String;

    /// Insert `text` at the current cursor position in the active editor,
    /// replacing any active selection.
    fn insert_text(&self, text: &str);

    /// Execute a named IDE command with a JSON-encoded argument string.
    /// Returns `Ok(output)` on success or `Err(message)` on failure.
    fn execute_command(&self, cmd: &str, args: &str) -> Result<String, String>;
}

/// The interface every plugin must implement. The IDE loads the shared
/// library, calls `_phazeai_plugin_create` (generated by `declare_plugin!`)
/// to obtain a boxed trait object, and drives it through this interface.
pub trait PhazePlugin {
    /// Short human-readable name, e.g. `"My Formatter"`.
    fn name(&self) -> &str;

    /// SemVer-style version string, e.g. `"0.1.0"`.
    fn version(&self) -> &str;

    /// One-sentence description shown in the plugin manager.
    fn description(&self) -> &str;

    /// Called once after the plugin is loaded. The `host` reference remains
    /// valid until `on_deactivate` returns.
    fn on_activate(&mut self, host: &dyn PluginHost);

    /// Called before the plugin is unloaded or the IDE shuts down. The
    /// plugin must release any resources that depend on `host` here.
    fn on_deactivate(&mut self);

    /// Return the list of commands this plugin contributes. The IDE
    /// registers them in the command palette and may bind keybindings.
    fn commands(&self) -> Vec<PluginCommand>;

    /// Execute one of the plugin's own commands. `cmd` is the `id` field
    /// from a `PluginCommand` returned by `commands()`. `args` is a
    /// JSON-encoded argument string (may be `"{}"` for no arguments).
    fn execute_command(&mut self, cmd: &str, args: &str) -> Result<String, String>;

    /// Receive an IDE event. The default implementation is a no-op; plugins
    /// that want event-driven behaviour should override it.
    fn on_event(&mut self, _event: &PluginEvent) {}
}

/// A command contributed by a plugin and surfaced in the IDE command palette.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PluginCommand {
    /// Stable identifier used to route `execute_command` calls.
    pub id: String,
    /// Display name shown in the command palette.
    pub title: String,
    /// Optional default keybinding, e.g. `"Ctrl+Shift+F"`.
    pub keybinding: Option<String>,
}

/// IDE events delivered to active plugins via `on_event`.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum PluginEvent {
    /// A file was opened in an editor tab.
    FileOpened { path: String },
    /// An editor tab was saved to disk.
    FileSaved { path: String },
    /// An editor tab was closed.
    FileClosed { path: String },
    /// The cursor moved within an editor tab. Lines and columns are 0-based.
    CursorMoved { line: u32, col: u32 },
    /// The text selection changed. `text` is the newly selected content.
    SelectionChanged { text: String },
    /// An application-defined event not covered by the variants above.
    /// `kind` is a dot-namespaced identifier; `data` is a JSON payload.
    Custom { kind: String, data: String },
}

/// Metadata describing a plugin, loaded from `plugin.json` alongside the
/// shared library before the library itself is opened.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PluginManifest {
    /// Must match `PhazePlugin::name()`.
    pub name: String,
    /// Must match `PhazePlugin::version()`.
    pub version: String,
    /// Human-readable description.
    pub description: String,
    /// Plugin author name or organisation.
    pub author: String,
    /// Lowest `API_VERSION` this plugin is compatible with.
    pub min_api_version: u32,
    /// Override the shared library file name. When `None` the IDE derives
    /// the name from `name` using the platform convention
    /// (`lib<name>.so` / `<name>.dll` / `lib<name>.dylib`).
    pub library: Option<String>,
}

/// Place this macro at the crate root of a plugin to generate the three
/// `extern "C"` entry-points the IDE loader calls.
///
/// The `$plugin_type` must implement `PhazePlugin + Default`.
///
/// # Example
///
/// ```rust,ignore
/// use phazeai_plugin_api::declare_plugin;
///
/// #[derive(Default)]
/// struct MyPlugin;
///
/// impl PhazePlugin for MyPlugin { /* … */ }
///
/// declare_plugin!(MyPlugin);
/// ```
#[macro_export]
macro_rules! declare_plugin {
    ($plugin_type:ty) => {
        /// Returns the API version this plugin was compiled against so the
        /// host can verify compatibility before calling further entry-points.
        #[no_mangle]
        pub extern "C" fn _phazeai_plugin_api_version() -> u32 {
            $crate::API_VERSION
        }

        /// Allocate a new plugin instance on the heap and return a fat
        /// pointer. The host takes ownership and must eventually call
        /// `_phazeai_plugin_destroy`.
        #[no_mangle]
        pub extern "C" fn _phazeai_plugin_create() -> *mut dyn $crate::PhazePlugin {
            let plugin: Box<dyn $crate::PhazePlugin> = Box::new(<$plugin_type>::default());
            Box::into_raw(plugin)
        }

        /// Drop the plugin instance previously returned by
        /// `_phazeai_plugin_create`. Passing a null pointer is safe (no-op).
        ///
        /// # Safety
        ///
        /// `plugin` must be a pointer returned by `_phazeai_plugin_create`
        /// from the same library and must not have been destroyed already.
        #[no_mangle]
        pub unsafe extern "C" fn _phazeai_plugin_destroy(plugin: *mut dyn $crate::PhazePlugin) {
            if !plugin.is_null() {
                let _ = Box::from_raw(plugin);
            }
        }
    };
}
