#!/usr/bin/env python3
"""
Train PhazeAI-GameDev - AAA Game Development Expert.
Uses collected game dev data and optimizes for 8GB VRAM.
"""

import json
from pathlib import Path
import sys

# Load config
script_dir = Path(__file__).parent
config_path = script_dir / "config" / "projects.json"

if config_path.exists():
    with open(config_path, 'r') as f:
        config = json.load(f)
else:
    print("ERROR: Config not found. Please ensure config/projects.json exists.")
    sys.exit(1)

# Get AI name from config
ai_name = config.get("ai_customization", {}).get("name", "phazeai")
model_name = ai_name.lower().replace(" ", "-")

# Paths
data_dir = script_dir / "data" / "gamedev-training"
output_dir = script_dir / "models" / f"{model_name}-gamedev"

print(f"\n{'='*60}")
print(f"Training {ai_name}-GameDev")
print(f"{'='*60}")
print(f"Data: {data_dir}")
print(f"Output: {output_dir}")
print(f"{'='*60}")

# Check for game dev data
if not data_dir.exists():
    print("Creating gamedev-training directory...")
    data_dir.mkdir(parents=True, exist_ok=True)
    
    print("\nGame development data sources:")
print("  - Godot Engine")
print("  - Bevy Engine")
print("  - Amethyst Engine")
print("  - Open Source Games:")
print("    - Minetest (Minecraft clone)")
print("    - OpenArena (FPS game)")
print("    - Xonotic (Arena FPS game)")
print("    - SuperTuxKart (Kart racing)")
print("  - Warsow (Arena FPS)")
print("{'='*60}")

# Create sample data if directory is empty
import os
sample_files = [
    "player_controller.gd",
    "physics_engine.rs",
    "game_loop.rs",
    "entity_manager.rs",
]

for fname in sample_files:
    fpath = data_dir / fname
    if not fpath.exists():
        with open(fpath, 'w') as f:
            f.write(f'// Sample {fname}\n// Generated by {ai_name}-GameDev\n\n')
        print(f"  Created sample: {fname}")

print("\n✅ Setup complete. Ready to train!")
print(f"\nTo start training, run:")
print(f"  python3 scripts/train_gamedev.py --epochs 2")
